import Head from "next/head";
import styles from "../styles/Home.module.scss";

// ** Components **
import Header from "../components/Header/Header";
import Menu from "../components/Menu/Menu";
import Welcome from "../components/Welcome/Welcome";

// ** Hooks **
import { useState, useEffect } from "react";

export default function Home() {
  const [userMenuFocus, setUserMenuFocus] = useState(0);

  return (
    <div className={[styles.Home].join(" ")}>
      <Head>
        <title>Mathieu Barisaux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Welcome />
    </div>
  );
}
